### ISSUE TITLE
spoiler (黒塗り)を 1 キーで開ける機能

### ISSUE THREAD

**Issue by tqkoh** [JichouP/Better-traQ#11]
選択しているメッセージの spoiler をクリックせずに開けたい。1 つのメッセージ中にいくつも spoiler があったらどうするかなど考える必要あり?
![image](https://user-images.githubusercontent.com/41860354/118454380-43953880-b733-11eb-827e-f1df1da59966.png)

**Comment by JichouP** [comment]
`j`, `k` でメッセージを選択して、該当メッセージの spoiler は全部開くのでよさそう

**Comment by JichouP** [comment]
`shown` で開いているかどうかわかるっぽい
`<span class="spoiler" shown></span>`
