### ISSUE TITLE
Actionsの関数をキー入力と分離する

### ISSUE THREAD

**Issue by anko9801** [JichouP/Better-traQ#13]
キーバインディングを後で作り今のActionsの関数と対応させることを前提にすると、機能とキー入力を完全に分離(関数の引数にキーイベントを入れない)すれば後々楽になると思いましたが、それはどうなのでしょうか？

**Comment by JichouP** [comment]
@anko9801 
僕は  `ev.preventDefault()` まで含めて「機能(Action)」だと考えているので、`KeyboardEvent` も一緒に渡すほうが良いと思います．
`ev` を渡しているAction関数は呼び出すときに必ず `preventDefault` を呼ぶので、分離したときに呼び忘れが起きないかが心配です．


後々楽になるかどうかは、JSONの形式によると思います．
例えば、このようなJSON形式にすれば、

```json
{
  "keyBinds": {
    "FOCUS_STAMP_PICKER_INPUT": "w"
  }
}
```

`keyDownHandler.ts` は次のように書くことができるため、`KeyboardEvent` を渡すことによるデメリットはなく、むしろ `action.ts` 側で `preventDefault` を呼んでいるため「これちゃんと `preventDefault` 呼んでいるのかな？」と確認する必要がなくなるため可読性も上がると思います．

```typescript
// keyDownHandler.ts
export const handler: (ev: KeyboardEvent) => void = async (ev) => {
  const { key } = ev;
  switch (key) {
    case keyBinds.FOCUS_STAMP_PICKER_INPUT:
      return Actions.focusNthFilterInput(ev, 2);
  }
}
```

```typescript
// action.ts
export const focusNthFilterInput = (event: KeyboardEvent, i: number): void => {
  event.preventDefault(); // KeyboardEventを渡さないとこの行がなくなるので、preventDefault も一緒に呼び出すことを担保できない
  getElements.filterInputs()[i]?.focus();
};
```

**Comment by anko9801** [comment]
なるほど、preventDefaultもまとめて機能としてみた方が読みやすくなるということですね。では、TabのclickOneChannelUpOrDown関数のシフトキー同時押しの処理をkeydownhandlerに置いて良いですか...？

**Comment by JichouP** [comment]
それはJSONを食わせる部分(`keyDownHandler.ts`)をもう少し綺麗に書くべきですね:pray:

その場合のJSON形式はこうですかね

```JSON
{
  "keyBinds": {
    "CLICK_ONE_CHANNEL_UP": {
      "code": "Tab",
      "modifiers": ["shiftKey"]
    },
    "CLICK_ONE_CHANNEL_DOWN": {
      "code": "Tab"
    }
  }
}
```
