### ISSUE TITLE
READMEにデフォルトのキーとそれに対応する機能を書く

### ISSUE THREAD

**Issue by anko9801** [JichouP/Better-traQ#18]
外から見て何ができるのかよくわからないので説明、できればgifなどを生成してわかりやすくするのがよさそう。

**Comment by anko9801** [comment]
v2.0.1に向けてデフォルトのキーバインドを良い感じにする大作戦です！いろいろと考えてみました～下にまとめておきました。
- Lでサイドバーを開くと同時に閲覧者を開く
- Eで未読開いて通り越してしまったらRで前に戻ってTで次に進める
- Fで上位階層、Dで下位階層へ
- あとウォッチモードをどこに置くか迷っています(安易に考えでVとかに置くとCtrl+Vで間違えてVを先に押しちゃったときに戸惑いそうなど

**Comment by anko9801** [comment]
ウォッチモード、"-"にします！

**Comment by JichouP** [comment]
いいと思います:+1:
この方針で進めていきましょう！
