### ISSUE TITLE
アクティビティのウォッチ機能ほしい

### ISSUE THREAD

**Issue by anko9801** [JichouP/Better-traQ#2]
ほしい！

**Comment by JichouP** [comment]
@anko9801 
具体的にどんな感じ？
新しいメッセージが来たら自動的にチャンネル移動するみたいな？

**Comment by anko9801** [comment]
そのとおりです！キーを押したら自動アクティビティ追従モードに入る感じです。戻り方はあまり想定してませんが、キー入力または大きなアクション(ナビゲーション移動など)があったら止める感じでしょうか。

**Comment by anko9801** [comment]
パッと思いつくのはメッセージのスタックをもって定期的に新しいものが存在するかを見て、あればスタックに追加してチャンネル移動でしょうか（要素更新イベントハンドラがあれば良いんですが

**Comment by anko9801** [comment]
#4

**Comment by JichouP** [comment]
@anko9801 
huskyの設定を誤っていたため、[修正しました](https://github.com/JichouP/Better-traQ/pull/4/commits/a7a58ef660ea8cf9d09c8d1c62511b25c6af8e42)
`scroll_messages` ブランチで `pull` してから
`npm run prepare` を叩いてhuskyを使用してください

また、今回はhuskyを通さずにコミットしたファイルあるため、
`npm run lint`
を叩いて lint エラーを確認して修正してください
